"""Generate a Kaggle script kernel that runs many candidates on many gates with every core of the VM.
usage: mkkernel.py spec.json out_script.py
spec = {"base": "sf8",
        "cands": {"sf8": "gold/top10/lean_sf8.py", "x": "gold/top10/cands/full_x.py", ...},
        "gates": {"top10g": ["sf8", "x"], "live191": [...], "cl": [...]},
        "cl": {"opps": ["omw_v15a", "pub_metav4v13"], "seeds": [6100, 6299], "seats": "01"},
        "gates_ds": "kagg-gates-0927", "opps_ds": "kagg-opps-0927"}
Candidates are stored as line diffs against the first candidate of their family (lean / full), so the script stays small.
The kernel writes rows_<gate>.jsonl (the same row format as the local gates, 'cand' = label) and summary.txt.
Local dry run: KW=<dir> KIN=<dir with gates.bin + opp files> MAXTASK=6 python out_script.py"""
import sys, os, json, zlib, base64, difflib
ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..'))
CODE = ['arena/lean.py', 'arena/decouple.py', 'gold/harness/pinned4.py', 'gold/harness/batch4.py', 'gold/elite/elite_gate.py',
        'gold/elite/transplant.py', 'gold/elite/eval_elite_routes.py', 'gold/elite/diag_collapse.py']


def rd(p):
    return open(os.path.join(ROOT, p), encoding='utf-8').read().replace('\r\n', '\n')


spec = json.load(open(sys.argv[1], encoding='utf-8'))
out = sys.argv[2]
code = {os.path.basename(p): rd(p) for p in CODE}
# the bases live in a private dataset (bases.bin: the kernel source must stay under 1 MB); candidates are diffs against them
BASES = {'lean': 'gold/top10/lean_sf8.py', 'full': 'gold/top10/full/sf8_full.py'}
bases = {fam: rd(p) for fam, p in BASES.items()}
import hashlib
spec['base_sha'] = {fam: hashlib.sha256(s.encode('utf-8')).hexdigest()[:16] for fam, s in bases.items()}
if len(sys.argv) > 3:
    open(sys.argv[3], 'wb').write(zlib.compress(json.dumps(bases).encode('utf-8'), 9))
    print('wrote bases', sys.argv[3], spec['base_sha'])
cands = {}
for lab, path in spec['cands'].items():
    src = rd(path)
    fam = 'lean' if 'GC_P = dict(div_over={}' in src else 'full'
    a, b = bases[fam].split('\n'), src.split('\n')
    sm = difflib.SequenceMatcher(None, a, b, autojunk=False)
    ops = [(i1, i2, b[j1:j2]) for tag, i1, i2, j1, j2 in sm.get_opcodes() if tag != 'equal']
    cands[lab] = dict(base=fam, ops=ops)
    print('cand', lab, fam, 'ops', len(ops), 'lines', sum(len(o[2]) for o in ops))
blob = base64.b85encode(zlib.compress(json.dumps(dict(code=code, cands=cands)).encode('utf-8'), 9)).decode()
head = '''# offhand: Kaggriculture gate runner (generated by gold/top10/kaggle/mkkernel.py)
import os
os.environ['OMP_NUM_THREADS'] = '1'
import sys, json, zlib, base64, subprocess, time, glob, collections, math
SPEC = %r
BLOB = %r
''' % (spec, blob)
body = r'''
W = os.environ.get('KW', '/kaggle/working')
KIN = os.environ.get('KIN', '/kaggle/input')
C = os.path.join(W, 'code')


def setup():
    try:
        import importlib.metadata as md
        v = md.version('kaggle-environments')
    except Exception:
        v = None
    if v != '1.32.7':
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-deps', 'kaggle-environments==1.32.7'], check=False)
        for dep in ('jsonschema', 'requests'):
            subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', dep], check=False)
    d = json.loads(zlib.decompress(base64.b85decode(BLOB)))
    import hashlib
    d['bases'] = json.loads(zlib.decompress(open(find('bases.bin'), 'rb').read()))
    for fam, sha in SPEC['base_sha'].items():
        got = hashlib.sha256(d['bases'][fam].encode('utf-8')).hexdigest()[:16]
        assert got == sha, ('base mismatch', fam, got, sha)
    os.makedirs(os.path.join(C, 'cands'), exist_ok=True)
    for n, s in d['code'].items():
        open(os.path.join(C, n), 'w', encoding='utf-8').write(s)
    for lab, c in d['cands'].items():
        lines = d['bases'][c['base']].split('\n')
        for i1, i2, rep in sorted(c['ops'], key=lambda o: -o[0]):
            lines[i1:i2] = rep
        open(os.path.join(C, 'cands', lab + '.py'), 'w', encoding='utf-8').write('\n'.join(lines))


def find(name):
    hits = sorted(glob.glob(os.path.join(KIN, '**', name), recursive=True))
    if not hits:
        raise SystemExit('missing input ' + name)
    return hits[0]


def run(t):
    sys.path.insert(0, C)
    kind = t[0]
    try:
        if kind == 'pin':
            import pinned4
            _, gate, lab, f, S = t
            r = pinned4.job((f, 0, 'offhand', os.path.join(C, 'cands', lab + '.py'), S))
        elif kind == 'elite':
            import elite_gate
            _, gate, lab, f, ref = t
            d = json.load(open(f, encoding='utf-8'))[0]
            r = elite_gate._play((d, ref, os.path.join(C, 'cands', lab + '.py')))
        else:
            import batch4
            _, gate, lab, opp, seed, seat = t
            r = batch4.job((os.path.join(C, 'cands', lab + '.py'), opp, seed, seat))
        r['cand'] = lab; r['gate'] = gate
        return r
    except Exception as e:
        import traceback
        return dict(gate=t[1], cand=t[2], m=None, err=repr(e), tb=traceback.format_exc()[-800:])


def summary(rows_by_gate, base):
    out = []
    for gate, rows in sorted(rows_by_gate.items()):
        by = collections.defaultdict(dict)
        for r in rows:
            if r.get('m') is None:
                continue
            key = (r.get('gid'), r.get('seat'), r.get('seed'), r.get('opp'))
            by[r['cand']][key] = r['m']
        b = by.get(base, {})
        out.append('== %s (base %s: %d rows, wins %d)' % (gate, base, len(b), sum(v > 0 for v in b.values())))
        for lab in sorted(by):
            if lab == base:
                continue
            ks = [k for k in by[lab] if k in b]
            if not ks:
                continue
            dd = [by[lab][k] - b[k] for k in ks]; n = len(dd); m = sum(dd) / n
            se = math.sqrt(sum((x - m) ** 2 for x in dd) / max(1, n - 1) / n) if n > 1 else 0
            wb = sum(b[k] > 0 for k in ks); wc = sum(by[lab][k] > 0 for k in ks)
            up = sum(1 for k in ks if b[k] <= 0 < by[lab][k]); dn = sum(1 for k in ks if by[lab][k] <= 0 < b[k])
            out.append('  %-22s n %4d  %+7.0f +- %4.0f  wins %4d -> %4d (+%d/-%d)' % (lab, n, m, se, wb, wc, up, dn))
    return '\n'.join(out)


if __name__ == '__main__':
    t0 = time.time()
    setup()
    sys.path.insert(0, C)
    data = json.loads(zlib.decompress(open(find('gates.bin'), 'rb').read()))
    tasks = []
    for gate, labs in SPEC['gates'].items():
        if gate in data['pinned']:
            g = data['pinned'][gate]; os.makedirs(os.path.join(W, 'g', gate), exist_ok=True)
            for i, d in enumerate(g['games']):
                if 'offhand' not in d['info']['TeamNames']:
                    continue
                f = os.path.join(W, 'g', gate, '%d.json' % i); json.dump([d], open(f, 'w', encoding='utf-8'))
                tasks += [('pin', gate, lab, f, g['S']) for lab in labs]
        elif gate in data['elite']:
            g = data['elite'][gate]; os.makedirs(os.path.join(W, 'g', gate), exist_ok=True)
            files = {}
            for d in g['games']:
                f = os.path.join(W, 'g', gate, '%d.json' % d['id']); json.dump([d], open(f, 'w', encoding='utf-8')); files[d['id']] = f
            for ref in g['refs']:
                tasks += [('elite', gate, lab, files[ref['gid']], ref) for lab in labs]
        elif gate == 'cl':
            cl = SPEC['cl']
            for opp in cl['opps']:
                of = find(opp + '.py')
                for seed in range(cl['seeds'][0], cl['seeds'][1] + 1):
                    for seat in [int(c) for c in cl['seats']]:
                        tasks += [('cl', 'cl_' + opp, lab, of, seed, seat) for lab in labs]
    del data
    if os.environ.get('MAXTASK'):
        tasks = tasks[:int(os.environ['MAXTASK'])]
    nproc = int(os.environ.get('NPROC', max(2, (os.cpu_count() or 4) - 2)))
    print('tasks', len(tasks), 'procs', nproc, 'setup', round(time.time() - t0), 's', flush=True)
    import multiprocessing as mp
    rows = collections.defaultdict(list); fh = {}
    done = 0
    with mp.get_context('spawn' if os.name == 'nt' else 'fork').Pool(nproc) as pool:
        for r in pool.imap_unordered(run, tasks, chunksize=1):
            g = r['gate']
            if g not in fh:
                fh[g] = open(os.path.join(W, 'rows_%s.jsonl' % g), 'w', encoding='utf-8')
            fh[g].write(json.dumps(r, ensure_ascii=False) + '\n'); fh[g].flush()
            rows[g].append(r); done += 1
            if done % 200 == 0 or done == len(tasks):
                print('done', done, '/', len(tasks), round(time.time() - t0), 's', flush=True)
            if done % 1000 == 0:
                open(os.path.join(W, 'summary.txt'), 'w').write(summary(rows, SPEC['base']))
    s = summary(rows, SPEC['base'])
    open(os.path.join(W, 'summary.txt'), 'w').write(s)
    print(s)
    errs = [r for g in rows.values() for r in g if r.get('tb')]
    print('errors', len(errs), (errs[0]['tb'] if errs else ''))
    print('elapsed', round(time.time() - t0), 's')
'''
src = head + body
compile(src, out, 'exec')
open(out, 'w', encoding='utf-8').write(src)
print('built', out, len(src), 'bytes')
